language: 
  - php

env:
  - LARAVEL_VERSION=5.2.*

matrix:
  include:
    - php: 5.5
      env: LARAVEL_VERSION=5.2.*
    
    - php: 5.6
      env: LARAVEL_VERSION=5.2.*
    - php: 5.6
      env: LARAVEL_VERSION=5.3.*
    - php: 5.6
      env: LARAVEL_VERSION=5.4.*
    
    - php: 7.0
      env: LARAVEL_VERSION=5.2.*
    - php: 7.0
      env: LARAVEL_VERSION=5.3.*
    - php: 7.0
      env: LARAVEL_VERSION=5.4.*
    
    - php: 7.1
      env: LARAVEL_VERSION=5.2.*
    - php: 7.1
      env: LARAVEL_VERSION=5.3.*
    - php: 7.1
      env: LARAVEL_VERSION=5.4.*
    
    - php: hhvm
      env: LARAVEL_VERSION=5.2.*
    - php: hhvm
      env: LARAVEL_VERSION=5.3.*
    - php: hhvm
      env: LARAVEL_VERSION=5.4.*

before_install:
  - travis_retry composer self-update
  - travis_retry composer require "laravel/framework:${LARAVEL_VERSION}" --no-interaction --no-update

install: 
  - travis_retry composer update --prefer-source --no-interaction

before_script:

script: 
  - vendor/bin/phpunit
